## Download and import vader

In [1]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()
nltk.downloader.download('vader_lexicon')

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/yidanzhang/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

## Import packages

In [2]:
import matplotlib.pyplot as plt
import os
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer

## Read all data from news.csv with head (已整理Title, Date, Time) 
## TODO: 重新整理content

In [3]:
sample_list = ["Title", "Date", "Time", "Content"]
sample_data = pd.read_csv('news_updated.csv', usecols=sample_list).astype(str) 
sample_data.head()

,Title,Date,Time,Content
0,Bitcoin price hits $34K as trader forecasts fr...,2021-07-24,15:46:15,"<p>Bitcoin (<a href=""https://cointelegraph.com..."
1,Bitcoin price hints at 'megaphone' bottom patt...,2021-07-24,13:42:02,"<p>Bitcoin's (<a href=""https://cointelegraph.c..."
2,Just HODL! Bitcoin and Ethereum outperform ‘lo...,2021-07-24,01:05:00,"<p>In the past two decades, index and exchange..."
3,"Price analysis 7/23: BTC, ETH, BNB, ADA, XRP, ...",2021-07-23,18:26:09,"<p>Bitcoin’s (<a href=""https://cointelegraph.c..."
4,Bitcoin payments for real estate gain traction...,2021-07-23,17:15:24,<p>Crypto investors are betting big on real es...

## Calculate Sentiment Scores

In [4]:
vader = SentimentIntensityAnalyzer()
content = sample_data['Content']
content = str(content).encode('utf-8')
scores = sample_data['Content'].apply(lambda content:vader.polarity_scores(content)).tolist()
scores_df = pd.DataFrame(scores)
scores_df.head()

   compound    neg    neu    pos
0    0.9811  0.011  0.903  0.085
1    0.8581  0.064  0.868  0.068
2    0.9961  0.031  0.841  0.128
3    0.9951  0.067  0.840  0.093
4    0.9966  0.012  0.905  0.083

## Add scores to original data frame

In [5]:
scored_news = sample_data.join(scores_df, rsuffix='_right')
scored_news.head()

,Title,Date,Time,Content,compound,neg,neu,pos
0,Bitcoin price hits $34K as trader forecasts fr...,2021-07-24,15:46:15,"<p>Bitcoin (<a href=""https://cointelegraph.com...",0.9811,0.011,0.903,0.085
1,Bitcoin price hints at 'megaphone' bottom patt...,2021-07-24,13:42:02,"<p>Bitcoin's (<a href=""https://cointelegraph.c...",0.8581,0.064,0.868,0.068
2,Just HODL! Bitcoin and Ethereum outperform ‘lo...,2021-07-24,01:05:00,"<p>In the past two decades, index and exchange...",0.9961,0.031,0.841,0.128
3,"Price analysis 7/23: BTC, ETH, BNB, ADA, XRP, ...",2021-07-23,18:26:09,"<p>Bitcoin’s (<a href=""https://cointelegraph.c...",0.9951,0.067,0.840,0.093
4,Bitcoin payments for real estate gain traction...,2021-07-23,17:15:24,<p>Crypto investors are betting big on real es...,0.9966,0.012,0.905,0.083

In [6]:
group_scored_news = scored_news.groupby("Date")
mean_scored_news = group_scored_news.mean()
mean_scored_news = mean_scored_news.reset_index()

In [7]:
mean_scored_news.head()

         Date  compound       neg       neu      pos
0  2018-12-25 -0.047950  0.043500  0.918000  0.03850
1  2018-12-26  0.687233  0.026833  0.912333  0.06100
2  2018-12-27 -0.203940  0.069800  0.881400  0.04880
3  2018-12-28  0.385650  0.048333  0.889167  0.06250
4  2018-12-29 -0.089475  0.065250  0.887000  0.04825

## Read k_line.csv (price)

In [10]:
col_list_price = ["Time", "Price", "Volume", "Change"]
parsed_price_data = pd.read_csv('price_volume.csv')
parsed_price_data.head()

         Time    Price   Volume   Change
0  1514736000  13371.5   293805    -0.32
1  1514736060  13405.5   219089    -0.25
2  1514736120  13450.0   651858    -0.33
3  1514736180  13528.0  1433129    -0.58
4  1514736240  13616.0  4301649    -0.65

In [11]:
from datetime import datetime
parsed_price_data['Time'] = [datetime.fromtimestamp(x) for x in parsed_price_data['Time']]
parsed_price_data[['Date','Time']] = parsed_price_data['Time'].astype(str).str.split(' ',expand=True)
parsed_price_data

            Time    Price   Volume   Change        Date
0       08:00:00  13371.5   293805    -0.32  2017-12-31
1       08:01:00  13405.5   219089    -0.25  2017-12-31
2       08:02:00  13450.0   651858    -0.33  2017-12-31
3       08:03:00  13528.0  1433129    -0.58  2017-12-31
4       08:04:00  13616.0  4301649    -0.65  2017-12-31
5       08:05:00  13683.0  2993575    -0.49  2017-12-31
6       08:06:00  13705.0  3148908    -0.16  2017-12-31
7       08:07:00  13687.0  4065627     0.13  2017-12-31
8       08:08:00  13690.0  2341692    -0.02  2017-12-31
9       08:09:00  13705.5   884267    -0.11  2017-12-31
10      08:10:00  13820.5  1636993    -0.84  2017-12-31
11      08:11:00  13913.0  2635568    -0.67  2017-12-31
12      08:12:00  13840.5  2755263     0.52  2017-12-31
13      08:13:00  13820.0   955120     0.15  2017-12-31
14      08:14:00  13863.0  1197491    -0.31  2017-12-31
15      08:15:00  13975.5  1084893    -0.81  2017-12-31
16      08:16:00  14019.0  2202506    -0.31  2017-12-31
17      08:17:00  14058.5  2067975    -0.28  2017-12-31
18      08:18:00  13980.0  2022299     0.56  2017-12-31
19      08:19:00  13857.0  2562756     0.88  2017-12-31
20      08:20:00  13871.5  1671290    -0.10  2017-12-31
21      08:21:00  13840.5  1199974     0.22  2017-12-31
22      08:22:00  13885.5  2241735    -0.33  2017-12-31
23      08:23:00  13927.0  1557983    -0.30  2017-12-31
24      08:24:00  13906.5   664979     0.15  2017-12-31
25      08:25:00  13911.0   453275    -0.03  2017-12-31
26      08:26:00  13821.0  1292028     0.65  2017-12-31
27      08:27:00  13852.0   613383    -0.22  2017-12-31
28      08:28:00  13865.0   196108    -0.09  2017-12-31
29      08:29:00  13860.5   380816     0.03  2017-12-31
...          ...      ...      ...      ...         ...
999969  06:36:00   7162.5  2001945    -0.13  2019-11-25
999970  06:37:00   7167.0  1079547    -0.06  2019-11-25
999971  06:38:00   7179.5   771562    -0.17  2019-11-25
999972  06:39:00   7177.5  1151466     0.03  2019-11-25
999973  06:40:00   7172.5  1179375     0.07  2019-11-25
999974  06:41:00   7178.0   605823    -0.08  2019-11-25
999975  06:42:00   7170.0  1712344     0.11  2019-11-25
999976  06:43:00   7175.5  1331382    -0.08  2019-11-25
999977  06:44:00   7175.0  1066774     0.01  2019-11-25
999978  06:45:00   7173.5   546389     0.02  2019-11-25
999979  06:46:00   7160.0  1358328     0.19  2019-11-25
999980  06:47:00   7162.5   871256    -0.03  2019-11-25
999981  06:48:00   7150.5  1466978     0.17  2019-11-25
999982  06:49:00   7151.5  1974054    -0.01  2019-11-25
999983  06:50:00   7149.5  1846837     0.03  2019-11-25
999984  06:51:00   7142.0  2601903     0.10  2019-11-25
999985  06:52:00   7143.0  2838553    -0.01  2019-11-25
999986  06:53:00   7149.0   895696    -0.08  2019-11-25
999987  06:54:00   7153.0  1288210    -0.06  2019-11-25
999988  06:55:00   7165.0  2341424    -0.17  2019-11-25
999989  06:56:00   7153.5   869978     0.16  2019-11-25
999990  06:57:00   7160.5  1148346    -0.10  2019-11-25
999991  06:58:00   7158.5   865118     0.03  2019-11-25
999992  06:59:00   7166.0  1917611    -0.10  2019-11-25
999993  07:00:00   7168.0  2721113    -0.03  2019-11-25
999994  07:01:00   7191.5  4464360    -0.33  2019-11-25
999995  07:02:00   7184.0  2898102     0.10  2019-11-25
999996  07:03:00   7182.5   820481     0.02  2019-11-25
999997  07:04:00   7190.0  1975713    -0.10  2019-11-25
999998  07:05:00   7212.0  5689980    -0.31  2019-11-25

[999999 rows x 5 columns]

In [17]:
volume_data = parsed_price_data[['Date', ' Volume']]
group_volume_data = volume_data.groupby("Date")
sum_volume = group_volume_data.sum()
sum_volume = sum_volume.reset_index()

In [18]:
sum_volume.head()

         Date     Volume
0  2017-12-31  454478678
1  2018-01-01  680516250
2  2018-01-02  944152848
3  2018-01-03  817351695
4  2018-01-04  698479219

In [54]:
parsed_circulating_data = pd.read_csv('total-bitcoins.csv')
parsed_circulating_data.head()

             Timestamp  total-bitcoins
0  2009-01-03 17:15:05            50.0
1  2009-01-14 12:25:25         22750.0
2  2009-01-18 11:33:45         45450.0
3  2009-01-22 18:27:35         68150.0
4  2009-01-25 17:15:02         90850.0

In [62]:
from datetime import datetime
parsed_circulating_data['Timestamp'] = [datetime.fromtimestamp(x) for x in parsed_price_data['Timestamp']]

KeyError: 'Timestamp'

## 截取疫情前后两个时间段的数据 (news, volume, circulating)
* 2019/01/01 - 2019/06/30 --> mask1
* 2020/01/01 - 2020/06/30 --> mask2

### 2019/01/01 - 2019/06/30

In [21]:
mean_scored_news['Date'] = pd.to_datetime(mean_scored_news['Date'])
mask1 = (mean_scored_news['Date'] >= '2019-1-1') & (mean_scored_news['Date'] <= '2019-6-30')
train_data1 = mean_scored_news.loc[mask1] #Index(['Date', 'compound', 'neg', 'neu', 'pos'], dtype='object')
train_data1.head()

         Date  compound       neg       neu       pos
7  2019-01-01 -0.284267  0.043500  0.924667  0.031667
8  2019-01-02  0.041388  0.043125  0.909750  0.047375
9  2019-01-03  0.375067  0.040667  0.888333  0.071500
10 2019-01-04  0.328850  0.039000  0.927500  0.033500
11 2019-01-05  0.331000  0.050500  0.893500  0.056000

In [23]:
sum_volume['Date'] = pd.to_datetime(sum_volume['Date'])
price_mask1 = (sum_volume['Date'] >= '2019-1-1') & (sum_volume['Date'] <= '2019-6-30')
train_volume_data1 = sum_volume.loc[price_mask1]
train_volume_data1

          Date       Volume
366 2019-01-01    979039368
367 2019-01-02   1097663564
368 2019-01-03    889059787
369 2019-01-04    923185106
370 2019-01-05    640874439
371 2019-01-06   1135382157
372 2019-01-07    983979089
373 2019-01-08   1299810701
374 2019-01-09   1300895254
375 2019-01-10   1288240535
376 2019-01-11    858668929
377 2019-01-12    528143513
378 2019-01-13    826889890
379 2019-01-14    894912891
380 2019-01-15    910891876
381 2019-01-16    878153114
382 2019-01-17    872234719
383 2019-01-18    624158867
384 2019-01-19    754614452
385 2019-01-20   1099003213
386 2019-01-21    730724684
387 2019-01-22   1160910545
388 2019-01-23    901105130
389 2019-01-24    700970415
390 2019-01-25    955722082
391 2019-01-26    660037436
392 2019-01-27   1470991649
393 2019-01-28   1160378784
394 2019-01-29    931328731
395 2019-01-30    784636623
..         ...          ...
517 2019-06-01   1404174300
518 2019-06-02   2867912919
519 2019-06-03   4704029679
520 2019-06-04   3974263254
521 2019-06-05   2955053871
522 2019-06-06   3174058633
523 2019-06-07   2582445828
524 2019-06-08   1660667052
525 2019-06-09   2913955463
526 2019-06-10   2529147987
527 2019-06-11   2639147081
528 2019-06-12   2463613180
529 2019-06-13   2301320266
530 2019-06-14   3388441448
531 2019-06-15   3933392950
532 2019-06-16   4989453734
533 2019-06-17   4539899575
534 2019-06-18   3681423430
535 2019-06-19   2267007959
536 2019-06-20   4288517995
537 2019-06-21   6593093134
538 2019-06-22   6685488213
539 2019-06-23   4989317719
540 2019-06-24   4526622114
541 2019-06-25   8567939759
542 2019-06-26  12637756895
543 2019-06-27  10877152270
544 2019-06-28   7822407616
545 2019-06-29   4882704544
546 2019-06-30   6366042556

[181 rows x 2 columns]

In [59]:
parsed_circulating_data['Date'] = pd.to_datetime(parsed_circulating_data['Timestamp'])
circulating_mask1 = (parsed_circulating_data['Date'] >= '2019-1-1') & (parsed_circulating_data['Date'] <= '2019-6-30')
train_circulating_data1 = parsed_circulating_data.loc[price_mask1]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

### 2020/01/01 - 2020/06/30

In [118]:
scored_news['Date'] = pd.to_datetime(scored_news['Date'])
mask2 = (scored_news['Date'] >= '2020-1-1') & (scored_news['Date'] <= '2020-6-30')
train_data2 = scored_news.loc[mask2]
train_data2

,Title,Date,Time,compound,neg,neu,pos
3915,Survey Shows 42% of Investors Expect a $15K Bi...,2020-06-30,22:03:00,0.0000,0.000,1.000,0.000
3916,3 Reasons Why Bitcoin Price Recorded Its Third...,2020-06-30,20:17:00,0.6369,0.000,0.704,0.296
3917,Bitcoin Scam Exposes Thousands to Data Breach,2020-06-30,16:55:00,-0.6369,0.510,0.490,0.000
3918,An Israeli Blockchain Startup Claims It’s Inve...,2020-06-30,15:00:00,0.0000,0.000,1.000,0.000
3919,Max Keiser: US Hash Rate War With Iran Can Sen...,2020-06-30,14:20:00,-0.5994,0.231,0.769,0.000
3920,Gold vs. Bitcoin: $2.8B Fake Bullion Scam High...,2020-06-30,10:13:00,-0.6369,0.415,0.427,0.159
3921,Bitcoin Price Bulls Pin Hopes on Descending Ch...,2020-06-30,07:43:00,0.4215,0.000,0.781,0.219
3922,Bitcoin’s ROI Since 2015 Outperforms Five Majo...,2020-06-30,05:44:00,0.0000,0.000,1.000,0.000
3923,Researchers Say New Lightning Network Attack C...,2020-06-29,22:38:00,-0.2500,0.254,0.574,0.172
3924,Bitcoin as a Tool to Fight Authoritarian Regim...,2020-06-29,22:18:00,-0.5719,0.343,0.657,0.000
3925,Researchers Say Ransomware Attacks on the Rise...,2020-06-29,21:04:00,-0.4404,0.195,0.805,0.000
3926,"Price Analysis 6/29: BTC, ETH, XRP, BCH, BSV, ...",2020-06-29,19:33:00,0.0000,0.000,1.000,0.000
3927,International Authorities Work Together to Tak...,2020-06-29,17:44:00,0.0000,0.000,1.000,0.000
3928,Bitcoin Dormant Supply Metric Mirrors 2016 Run...,2020-06-29,16:00:00,0.0000,0.000,1.000,0.000
3929,OKEx Announced The Listing of Compound DeFi Pr...,2020-06-29,15:25:00,0.0000,0.000,1.000,0.000
3930,Beyond Bitcoin: How Advances in Blockchain Can...,2020-06-29,14:19:00,0.4404,0.000,0.775,0.225
3931,Bitcoin Miners Done Selling? 5 Things to Know ...,2020-06-29,10:02:00,0.0000,0.000,1.000,0.000
3932,Crypto Research Report Predicts $397K Bitcoin ...,2020-06-29,09:21:00,0.0000,0.000,1.000,0.000
3933,Bitcoin Price Must Flip This Level Into Suppor...,2020-06-29,08:30:00,-0.1531,0.253,0.588,0.159
3934,Andreas Antonopoulos: Use DeFi Contracts for B...,2020-06-29,07:47:00,0.2023,0.000,0.816,0.184
3935,Blockchain Can Provide the Right to Privacy Th...,2020-06-28,21:00:00,0.0000,0.000,1.000,0.000
3936,New Bitcoin Price Model Suggests ‘Exponential’...,2020-06-28,20:32:00,0.0000,0.000,1.000,0.000
3937,Top 5 Cryptocurrencies to Watch This Week: BTC...,2020-06-28,19:21:00,0.2023,0.000,0.847,0.153
3938,Crypto Derivatives Might Drive a New Cycle of ...,2020-06-28,19:00:00,0.0000,0.000,1.000,0.000
3939,"PayPal Crypto Rumors, RIP Wirecard, Telegram S...",2020-06-28,18:30:00,0.0000,0.000,1.000,0.000
3940,What Recent Developments in the Fintech Space ...,2020-06-28,17:00:00,0.0000,0.000,1.000,0.000
3941,Experts Split on Practical Implications of Qua...,2020-06-28,15:00:00,0.0000,0.000,1.000,0.000
3942,Nonfungible Tokens Could Change the Way We Own...,2020-06-28,15:00:00,0.0000,0.000,1.000,0.000
3943,When Big Ben Rings: UK FCA’s Stance on Crypto ...,2020-06-28,13:45:00,0.2500,0.115,0.710,0.175
3944,Ransomware Gang Failed to Deploy an Attack Aga...,2020-06-28,01:00:00,-0.7506,0.416,0.584,0.000
...,...,...,...,...,...,...,...
5887,Ronnie Moas and Vinny Lingham Come to Blows Ov...,2020-01-05,17:30:00,0.0000,0.000,1.000,0.000
5888,Bitcoin Nears $7.5K: Why a Bull Market Is Clos...,2020-01-05,17:26:00,0.0000,0.000,1.000,0.000
5889,Bitcoin Network SegWit Adoption Hits 66% After...,2020-01-05,14:30:00,0.0000,0.000,1.000,0.000
5890,Richard Heart’s HEX Now Trading For Less Than ...,2020-01-05,09:21:00,-0.2732,0.160,0.840,0.000
5891,Biggest Crypto Price Movements of 2019,2020-01-05,01:53:00,0.0000,0.000,1.000,0.000
5892,Here’s What Must Happen for $9K Bitcoin Price ...,2020-01-04,15:55:00,0.0000,0.000,1.000,0.000
5893,Thanks Boomer? Bitcoin Friendly Generations to...,2020-01-04,12:58:00,0.7269,0.000,0.534,0.466
5894,Burger King Venezuela Starts Bitcoin Payments ...,2020-01-04,09:52:00,0.0000,0.000,1.000,0.000
5895,"Bitcoin Selling for $24,000 in Iran Based on ‘...",2020-01-04,09:50:00,0.0000,0.000,1.000,0.000
5896,5 More Bearish Candlestick Patterns Every Bitc...,2020-01-04,09:16:00,0.0000,0.000,1.000,0.000
5897,How Blockchain Can Improve Globalization,2020-01-03,19:56:00,0.4404,0.000,0.580,0.420
5898,"Price Analysis Jan 03: BTC, ETH, XRP, BCH, LTC...",2020-01-03,18:58:00,0.0000,0.000,1.000,0.000
5899,Bitcoin Back Above $7K as a Higher Low Can Spa...,2020-01-03,16:34:00,-0.0516,0.150,0.714,0.136
5900,US Citizen Indicted for Narcotics Distribution...,2020-01-03,12:14:00,0.0000,0.000,1.000,0.000
5901,Bitcoin Can Hit $50K in 2020 ‘Very Easily’ — N...,2020-01-03,10:52:00,0.0000,0.000,1.000,0.000
5902,Bitcoin and Oil Rally as US Kills Iran’s Top G...,2020-01-03,08:02:00,-0.4939,0.298,0.595,0.107
5903,Mining Giant Bitmain May Lay Off Another 50% o...,2020-01-02,21:40:00,0.0000,0.000,1.000,0.000
5904,Bitcoin Price Falls Below $7K But Bears Yet to...,2020-01-02,20:09:00,0.4019,0.000,0.816,0.184
5905,‘Cryptocurrency Will Not Die’: Mainstream Medi...,2020-01-02,15:55:00,0.0000,0.000,1.000,0.000
5906,Why the Fed Needs to Start Issuing Digital Dol...,2020-01-02,14:30:00,0.0000,0.000,1.000,0.000
5907,Former Barclays Exec to Launch UK’s First Regu...,2020-01-02,12:50:00,0.0000,0.000,1.000,0.000
5908,Andreessen Horowitz: Bitcoin Will Usher in ‘In...,2020-01-02,11:38:00,0.0000,0.000,1.000,0.000
5909,Bitcoin Kicks Off 2020 More Secure Than Ever a...,2020-01-02,09:14:00,0.4005,0.000,0.817,0.183
5910,Friendly Fraud and the Failure of Chargeback P...,2020-01-02,08:30:00,-0.5994,0.464,0.327,0.209
5911,Privacy Coins in 2019: True Financial Freedom ...,2020-01-02,03:30:00,0.8979,0.000,0.391,0.609
5912,"Bitcoin Price Will Crash Below $1k in 2020, Ze...",2020-01-01,22:15:00,-0.4019,0.197,0.803,0.000
5913,"Price Analysis Jan 01: BTC, ETH, XRP, BCH, LTC...",2020-01-01,18:15:00,0.0000,0.000,1.000,0.000
5914,Bitcoin: 4 Big Competitive Advantages Over Alt...,2020-01-01,12:14:00,0.4939,0.000,0.588,0.412
5915,"Bitcoin Must Gain 13,800% in 2020 to Stop John...",2020-01-01,08:56:00,0.2960,0.133,0.663,0.205
5916,Worst Bitcoin Price Prediction of 2019,2020-01-01,01:00:00,-0.6249,0.451,0.549,0.000

In [120]:
parsed_price_data['Date'] = pd.to_datetime(parsed_price_data['Date'])
price_mask2 = (parsed_price_data['Date'] >= '2020-1-1') & (parsed_price_data['Date'] <= '2020-6-30')
train_price_data2 = parsed_price_data.loc[price_mask2]
train_price_data2

             Time   Price       Date
1056201  00:00:00  7183.0 2020-01-01
1056202  00:01:00  7180.5 2020-01-01
1056203  00:02:00  7180.5 2020-01-01
1056204  00:03:00  7180.5 2020-01-01
1056205  00:04:00  7180.5 2020-01-01
1056206  00:05:00  7180.5 2020-01-01
1056207  00:06:00  7180.5 2020-01-01
1056208  00:07:00  7181.0 2020-01-01
1056209  00:08:00  7180.5 2020-01-01
1056210  00:09:00  7180.5 2020-01-01
1056211  00:10:00  7180.5 2020-01-01
1056212  00:11:00  7178.0 2020-01-01
1056213  00:12:00  7175.0 2020-01-01
1056214  00:13:00  7174.5 2020-01-01
1056215  00:14:00  7168.0 2020-01-01
1056216  00:15:00  7164.5 2020-01-01
1056217  00:16:00  7166.0 2020-01-01
1056218  00:17:00  7166.0 2020-01-01
1056219  00:18:00  7165.5 2020-01-01
1056220  00:19:00  7165.5 2020-01-01
1056221  00:20:00  7165.5 2020-01-01
1056222  00:21:00  7168.0 2020-01-01
1056223  00:22:00  7167.5 2020-01-01
1056224  00:23:00  7168.5 2020-01-01
1056225  00:24:00  7169.0 2020-01-01
1056226  00:25:00  7169.0 2020-01-01
1056227  00:26:00  7169.0 2020-01-01
1056228  00:27:00  7168.5 2020-01-01
1056229  00:28:00  7168.5 2020-01-01
1056230  00:29:00  7168.5 2020-01-01
...           ...     ...        ...
1318555  23:30:00  9132.5 2020-06-30
1318556  23:31:00  9132.5 2020-06-30
1318557  23:32:00  9133.0 2020-06-30
1318558  23:33:00  9132.5 2020-06-30
1318559  23:34:00  9137.5 2020-06-30
1318560  23:35:00  9138.0 2020-06-30
1318561  23:36:00  9138.0 2020-06-30
1318562  23:37:00  9138.5 2020-06-30
1318563  23:38:00  9138.0 2020-06-30
1318564  23:39:00  9138.0 2020-06-30
1318565  23:40:00  9137.5 2020-06-30
1318566  23:41:00  9137.5 2020-06-30
1318567  23:42:00  9138.0 2020-06-30
1318568  23:43:00  9138.0 2020-06-30
1318569  23:44:00  9138.5 2020-06-30
1318570  23:45:00  9138.5 2020-06-30
1318571  23:46:00  9138.5 2020-06-30
1318572  23:47:00  9139.0 2020-06-30
1318573  23:48:00  9138.5 2020-06-30
1318574  23:49:00  9138.5 2020-06-30
1318575  23:50:00  9138.5 2020-06-30
1318576  23:51:00  9138.0 2020-06-30
1318577  23:52:00  9138.5 2020-06-30
1318578  23:53:00  9138.0 2020-06-30
1318579  23:54:00  9138.5 2020-06-30
1318580  23:55:00  9138.5 2020-06-30
1318581  23:56:00  9138.5 2020-06-30
1318582  23:57:00  9138.5 2020-06-30
1318583  23:58:00  9138.0 2020-06-30
1318584  23:59:00  9138.0 2020-06-30

[262384 rows x 3 columns]